name: sirius_mortgage
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  modal_bottom_sheet: ^3.0.0
  intl: ^0.18.0
  google_fonts: ^6.2.1

  flutter_gen: any
dev_dependencies:
  # Lints
  flutter_lints: ^3.0.0

  # Tests
  flutter_test:
    sdk: flutter
  test: ^1.24.9

flutter_gen:
  output: lib/core/gen/resource

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/