name: sirius_mortgage
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  modal_bottom_sheet: ^3.0.0
  bloc: ^8.1.3
  intl: ^0.18.0
  equatable: ^2.0.5
  bloc_concurrency: ^0.2.4
  google_fonts: ^6.2.1
  flutter_bloc: ^8.1.5
  meta: ^1.11.0
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  shared_preferences: ^2.2.2
  json_annotation: ^4.8.1
  fl_chart: ^0.66.2
  firebase_core: ^2.27.2
  firebase_crashlytics: ^3.4.20

dev_dependencies:
  # Lints
  flutter_lints: ^3.0.1

  # Tests
  test: ^1.24.9

  # Codegeneration
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter_gen:
  output: lib/core/gen/resource

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/